### ISSUE TITLE
有使用方法的说明吗

### ISSUE THREAD

**Issue by westfly** [feilengcui008/tcplayer#3]
cmd --help 的确有些选项出来，但选项如何组合在一起？
比如
1. 如何抓包保存
2. 如何在线转发（源端口，目的端口）
3. 如何利用抓包文件进行转发、放大流量
谢谢作者解答

**Comment by feilengcui008** [comment]
1.不支持保存
2.这个程序是在要抓取流量的目标机器上运行的，-bpf参数指定bpf规则过滤特定端口的流量，目的回放ip和端口通过-raddr指定
3.放大通过并发客户端-concurrency，放大倍数-clone，是否建立长连接-long控制
